### ISSUE TITLE
UI - Bulb user control

### ISSUE THREAD

**Issue by LasseWormark** [clarkio/live-stream#5]
**Viewer color control**

1.  Implement a queue system, and a timer for each light change request, so if multiple people write the command each person get the requested color for ex. 5 seconds.

2. in the HUD / Overlay add a "light controlled by : username" in the time span the light is controlled by a user, and then give points towards how long time the light is controlled to give some viewer credit "only an idea"  💃

**Comment by clarkio** [comment]
I really like this idea and have it in the queue to work on a solution for it. Thanks for the suggestion @LasseWormark!

**Comment by clarkio** [comment]
Moved to client repo for better visibility and tracking: https://github.com/clarkio/ttv-chat-light/issues/42
